### ISSUE TITLE
label ‘scaler_1’ used but not defined   goto scaler_1

### ISSUE THREAD

**Issue by moshix** [bisqwit/that_terminal#9] opened 2019-05-05 15:10 UTC
I know it's still in development but for a few weeks now, even though there have been some source updates, I haven't been able to build this anymore because of the above error. 

Does the makefile need updating?

thanks a lot, love watching the development of this terminal. Very educational.

**Comment by bisqwit** [comment] 2019-05-05 17:27
Closed as duplicate of #7. See #7 for answers to this question.

**Closed as completed by bisqwit** 2019-05-05 17:27 UTC
